credentials:
  client_id: FOe2Zknn9tlK2A
  password: a2Bsomjjw2ea3i75
  secret_key: 2gvs2CstozHX2wYSkErEHf4yr5w
  user_agent: reddit_bot
  username: _BTA
custom_values:
  img_limit: 30
  sort_by: hot
  sub: wallpapers
